// This file is autogenerated. Do not edit manually.
export const lastUpdated = {
  privacyPolicy: {
    en: 'April 26, 2025',
    ru: '26 апреля 2025 г.',
    pl: '26 kwietnia 2025',
  },
  termsOfUse: {
    en: 'April 26, 2025',
    ru: '26 апреля 2025 г.',
    pl: '26 kwietnia 2025',
  },
};
